const cards = [
  ["Ahora se prohíbe", null, "en los aviones."],
  ["Es una pena que los niños de ahora se involucren en", null],
  ["En 1,000 años cuando el dinero en papel solo sea una memoria lejana,", null, "va a ser nuestra moneda nacional"],
  ["La federación Mexicana de Futbol ahora prohíbe", null, "por que les da una ventaja injusta a los jugadores"],
  ["¿Qué placer culpable tiene Batman?", null],
  ["El siguiente libro de J.K Rowling: Harry Potter y la Cámara de", null],
  ["Disculpe maestro, no acabe la tarea porque", null],
  ["Qué traje de regreso de mis vacaciones", null],
  ["¿", null, "? Hay una aplicación para eso"],
  [null, "¡A que uno no te basta!"],
  ["¿Cuál es mi anti-droga?", null],
  ["Mientras que los estados Unidos competían contra la union Soviética para llegar a la luna, el gobierno mexicano gastaba millones de pesos en investigación para ", null],
  ["En una nueva telenovela de Televisa, Belinda tiene problemas con ", null , " por primera vez"],
  ["¿Cual es mi poder secreto?", null],
  ["¿Cuál es la nueva dieta maravilla?", null],
  ["¿Qué es lo que cenaba El santo?", null],
  ["Cuando el faraón no reaccionó, Moisés invocó una plaga de ", null],
  ["¿Cómo mantengo el fuego en mi relación amorosa?", null],
  ["¿Que es lo más crujiente?", null],
  ["En la cárcel dicen que puedes cambiar 200 cigarros por", null],
  ["Después del terremoto, Niurka les llevó ", null, " a los Haitianos"],
  ["Santa Clos ahora les da ", null , " a los niños en vez de carbón"],
  ["La vida de los indígenas cambió para siempre cuando los españoles trajeron ", null],
  ["¿Qué utiliza la SEP para motivar a los niños a estudiar?", null],
  ["Quizá lo trae de nacimiento, Quizá tiene ", null],
  ["En los últimos momentos, Michael Jackson pensó en", null],
  ["A la gente blanca le gusta ", null],
  ["¿Porqué me duele todo?", null],
  ["Una cena romántica a la luz de las velas no estaría completa sin ", null],
  ["Si viajará al pasado, ¿Que llevaría para convencer a la gente de que soy un hechicero poderoso?", null],
  ["Llame ya para adquirir un ", null, " Nuestras operadoras esperan su llamada"],
  ["El viaje escolar quedó totalmente arruinado por ", null],
  ["¿Cuál es el mejor amigo de una mujer?", null],
  ["Doctor Corazón, estoy teniendo problemas con ", null, " y quisiera su consejo"],
  ["Cuando sea presidente de México, crearé la secretaría de", null],
  ["¿Qué es lo que me ocultan mis papás?", null],
  ["¿Qué es lo que nunca falla para animar las fiestas?", null],
  ["¿Qué mejora con la edad?", null],
  [null, " es bueno hasta la última gota"],
  ["Ojala no hubiera perdido el manual de ", null],
  [null, "¡Es una emboscada! (It´s a trap!)"],
  ["El nuevo reality de MTV se trata de 8 celebridades fracasadas viviendo con ", null],
  ["¿Qué cosa le parecería perturbadora pero extrañamente encantadora a la abuela?", null],
  ["¿Qué es lo más emo?", null],
  ["Mientras tengo sexo, me gusta pensar en ", null],
  ["¿Que hizo que terminara mi relación anterior?", null],
  ["¿Qué es ese sonido?", null],
  [null, "Así es como quiero morir"],
  ["¿Porqué estoy pegajoso?", null],
  ["¿Cuál es el siguiente juguete de la cajita feliz?", null],
  ["¿De que cosa hay demasiado en el cielo?", null],
  ["No se con que armas se peleará en la tercera guerra mundial, pero la cuarta guerra mundial se peleará con ", null],
  ["¿Qué funciona siempre para ligar?", null],
  [null, ": preferido por los niños, aprobado por las mamás"],
  ["¿Porqué no puedo dormir en la noche?", null],
  ["¿A que huele?", null],
  ["¿Qué ayuda a que Felipe Calderón se relaje?", null],
  ["El mundo se va a acabar, el mundo se va a acabar,", null, " es lo que nos va a matar."],
  ["Próximamente,", null, ": El musical."],
  ["Los antropólogos han descubierto una tribu primitiva que venera ", null],
  ["Entes de matarlo, Sr Bond, déjeme mostrarle ", null],
  ["Estudios revelan que las ratas encuentran la salida de un laberinto 50% más rápido después de ser expuestas a", null],
  ["A continuación en ESPN2: El campeonato Mundial de ", null],
  ["Cuando sea billonario, construiré una estatua de 20 metros que conmemore ", null],
  ["Para atraer más visitantes, el museo Smithsoniano de ciencias naturales ha abierto una exhibición interactiva de ", null],
  ["¡Guerra! ¿Para que sirve?", null],
  ["¿Qué hace que me llene de gases?", null],
  ["¿A que huelen los viejitos", null],
  ["¿Qué estoy dispuesto a sacrificar para la cuaresma?", null],
  ["La medicina alternativa ahora utiliza los poderes curativos de ", null],
  ["¿Con que ayudan a las comunidades tarahumaras?", null],
  ["¿Qué es lo que prefiere Carlos Salinas?", null],
  ["Durante su poco conocido periodo café, Picasso produjo cientos de pinturas de", null],
  ["¿Qué no quisieras encontrarte en tu comida china?", null],
  ["Yo tomo para olvidar", null],
  [null, "¡Chócalas cuate!"]
]

export default cards